version: "3.9"

services:
  db:
    image: postgres:15
    container_name: citas_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: citas_backend
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: citas_frontend
    restart: always
    env_file: .env
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
